### ISSUE TITLE
Не подключиться к БПЛА

### ISSUE THREAD

**Issue by Opressor-3000** [TEHGAM/Team_Tactics#1]
В открытом терминале не подключится ни к одному беспилотнику.

**Comment by Tourorist** [comment]
Есть у кого-либо из наших какие-нибудь идеи по этому поводу — в чем тут может быть проблема? Подскажите, пожалуйста, хотя бы какие здесь файлы нужно смотреть, чтобы разобраться в причине.

@a11archer, @KaMeG, @Noart537, @tym32167

**Comment by KaMeG** [comment]
Если беспилотника нет в списке дронов, то попробуй подойти к нему — возможно его необходимо предварительно «взломать» и переманить на свою сторону.

**Comment by tym32167** [comment]
1. Убедиться, что пользуешься терминалом своей стороны. 
2. Убедиться, что поставлен беспилотник за твою сторону. Он может быть и нейтральным, но тогда к нему надо ехать и его хакать. Если беспилотник за противника поставлен, то никак не подключиться.

**Comment by tym32167** [comment]
На карте нашел только 2 синих беспилотника ([раз](https://github.com/TEHGAM/Tactical-Patrol/blob/master/cox_patrol-ops-3-01-nato.Altis2/mission.sqm#L2003) и [два](https://github.com/TEHGAM/Tactical-Patrol/blob/master/cox_patrol-ops-3-01-nato.Altis2/mission.sqm#L2014)), у красных получается их нет.

**Comment by Opressor-3000** [comment]
БПЛА был поставлен на карту как пустой. Не знаю правильно ли это, может он должен быть за синию фракцию установлен ИМХО.Кто может распаковать и проверить эту версию?

PS: хакнуть не возможно — проверено.

**Comment by tym32167** [comment]
Чтобы БПА был в терминале, он должен быть за твою фракцию.

**Comment by Tourorist** [comment]
Вы случаем еще не успели проверить, была ли эта проблема решена тем [недавним изменением](https://github.com/TEHGAM/Team_Tactics/commit/c1c7653243ccb2af486b808e336f1a7386c93a0a)?

**Comment by ussrlongbow** [comment]
В беспилотнике поставленном за определенную фракцию внутри сидит виртуальный пилот и стрелок, соответственно суть получения управления БПЛА — получение управления виртуальным ботом, который сидит внутри БПЛА, если поставить пустой — внутри никого не будет и никого туда без скриптов не посадить.
