### ISSUE TITLE
Статичные отделения

### ISSUE THREAD

**Issue by Norad2142** [TEHGAM/Team_Tactics#15]
Требуется сделать так, чтобы отделения в лобби сервера полностью соответствовали отделениям в игре.

Мной наблюдалась такая проблема, что встав на пустом сервере, например, на слот в отделении **Альфа 2-3**, а потом прогрузившись — обнаруживал, что мое отделение называется **Альфа 1-1**. То есть, отделения формируются динамически при старте на карту. Как бы это обойти?

@a11archer @AlNazir

**Comment by Opressor-3000** [comment]
Решение уже найдено. Закрываю задачу.
