### ISSUE TITLE
Полная переработка Слотов и Групп

### ISSUE THREAD

**Issue by Opressor-3000** [TEHGAM/Team_Tactics#3]
В соответствии с этим списком:
#### Группа 1
1. Командир
2. Зам. Командира
#### Группа 2 — отделение пехоты

1 Командир Отделения
2. Командир Звена БПЛА Дартер
3. Медик
4. Снайпер 7.62
5. Пулеметчик
6. Стрелок ПТ
7. Стрелок ПВО
8. Командир Звена
9. Медик
10. Подрывник Сапер Инженер 
11. Стрелок ГП
12. Стрелок ГП
#### Группа 3 — oтделение пехоты
1. Командир Отделения
2. Командир Звена БПЛА Дартер
3. Медик
4. Снайпер 7.62
5. Пулеметчик
6. Стрелок ПТ
7. Стрелок ПВО
8. Командир Звена
9. Медик
10. Подрывник Сапер Инженер 
11. Стрелок ГП
12. Стрелок ГП
#### Группа 4 — экипаж РСЗО
1. Экипаж РСЗО
2. Экипаж РСЗО
3. Экипаж РСЗО
#### Группа 5 — экипаж САУ
1. Экипаж САУ
2. Экипаж САУ
3. Экипаж САУ
#### Группа 6 — экипаж танка
1. Экипаж танка Механик
2. Экипаж танка
3. Экипаж танка
#### Группа 7 — экипаж СЗУ
1. Экипаж СЗУ Механик
2. Экипаж СЗУ
3. Экипаж СЗУ
#### Группа 8
1. Пилот Истребителя
#### Группа 9
1. Пилот Боевого Вертолета
2. Стрелок Боевого Вертолета
#### Группа 10
1. Пилот Вертолета
2. Пилот Вертолета
3. Пилот Вертолета
4. Пилот Вертолета
#### Группа 11
1. Снайпер
2. Корректировщик
#### Группа 12
1. Снайпер
2. Корректировщик 
#### Группа 13
1. Оператор БПЛА
2. Оператор БПЛА
3. Оператор БПЛА
4. Оператор БПЛА

В дальнейшем слоты будут прикреплены к определенной технике.

**Comment by Tourorist** [comment]
@AlNazir, может сам спискок экипажа (4, 5, 6, 7) растолковать по ролям — водитель, стрелок, командир — в зависимости от техники?

**Comment by Opressor-3000** [comment]
@Tourorist, я уже думал об этом. Дело в том что если будет по ролям то придется каждый слот привязывать к месту в технике, а так только группу надо привязать к технике. И это будет более удобнее для игарков в группе.
