### ISSUE TITLE
Разрешение на технику

### ISSUE THREAD

**Issue by Opressor-3000** [TEHGAM/Team_Tactics#6]
Установить классовое ограничение на использование боевой техники. Таким образом, чтобы возможность занятия в ней конкретных мест (командир, стрелок, водитель) определялась в соответствии с выбранной игроком специальностью.

**Comment by Opressor-3000** [comment]
Norad сказал что нашёл скрипт. В ближайшее время будем добавлять и смотреть как работает. 

Помимо техники, доступ также нужно будет ограничить к некоторым видам оружия и приспособлений.

**Comment by Tourorist** [comment]
**[Norad](http://www.tehgam.com/memberlist.php?mode=viewprofile&u=168)** вроде как уже решил эту задачу в последнем коммите (70143da).

@AlNazir, закрывай что-ли.

**Comment by Opressor-3000** [comment]
Задача успешно выполнина.
