### ISSUE TITLE
Удалить Ранение

### ISSUE THREAD

**Issue by Opressor-3000** [TEHGAM/Team_Tactics#9]
Убрать систему ранений из миссии т.к будет добавлен мод [AGM](/KoffeinFlummi/AGM).

@tym32167 @a11archer

**Comment by Opressor-3000** [comment]
Эта задача выполнена.

Я не знаю как тут завершить задачу, поэтому прошу @Tourorist.

**Comment by tym32167** [comment]
@AlNazir, внизу есть кнопочка **Close Issue** — если начать вводить комментарий, то она уже будет называться **Close and comment**. Вот она и закрывает задачу.
